---

- hosts: all
  pre_tasks:
    - name: include configuration for current OS
      include_vars: "{{ ansible_distribution }}/{{ ansible_distribution_release }}/kernels.yml"
      tags:
        - setup
        - dkms
        - retrieval
        - backports

  roles:
    - backports
    - setup
    - dkms
    - retrieval
