---

# unarchive
# get_url
- hosts: localhost
  tasks:
    - name: download drivers
      unarchive:
        src: "{{ item.value.url }}"
        dest: /usr/src
        copy: no
        creates: "/usr/src/{{ item.key }}-{{ item.value.version }}"
      with_dict: "{{ drivers }}"

    - name: generate dkms.conf
      template:
        src: dkms.conf.j2
        dest: "/usr/src/{{ item.key }}-{{ item.value.version }}/dkms.conf"
      with_dict: "{{ drivers }}"

# add -k option to dkms https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support#DKMS_package_creation

    - name: dkms add
      shell: "dkms add -m {{ item.key }} -v {{ item.value.version }}"
      args:
        creates: "/var/lib/dkms/{{ item.key }}/{{ item.value.version }}"
      with_dict: "{{ drivers }}"

    - name: dkms build
      shell: "dkms build -m {{ item.key }} -v {{ item.value.version }}"
      with_dict: "{{ drivers }}"

    - name: dkms mkbmdeb
      shell: "dkms mkbmdeb -m {{ item.key }} -v {{ item.value.version }}"
      with_dict: "{{ drivers }}"
