---

# unarchive
# get_url
- hosts: localhost
  tasks:
    - name: download drivers
      unarchive:
        src: "{{ item.value.url }}"
        dest: /usr/src
        copy: no
        creates: "/usr/src/{{ item.key }}-{{ item.value.version }}"
      with_dict: "{{ drivers }}"

    - name: generate dkms.conf
      template:
        src: dkms.conf.j2
        dest: "/usr/src/{{ item.key }}-{{ item.value.version }}/dkms.conf"
        force: no
      with_dict: "{{ drivers }}"

    - name: install wanted kernel
      apt:
        name: "{{ item }}"
      with_items:
        - "linux-image-{{ kernel_version }}-{{ kernel_arch }}"
        - "linux-headers-{{ kernel_version }}-{{ kernel_arch }}"

# add -k option to dkms https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support#DKMS_package_creation

    - name: dkms add
      shell: "dkms add -m {{ item.key }} -v {{ item.value.version }} -k {{ kernel_version }}-{{ kernel_arch }}"
      args:
        creates: "/var/lib/dkms/{{ item.key }}/{{ item.value.version }}"
      with_dict: "{{ drivers }}"

    - name: dkms build
      shell: "dkms build -m {{ item.key }} -v {{ item.value.version }} -k {{ kernel_version }}-{{ kernel_arch }}"
      with_dict: "{{ drivers }}"

      # Not working for the moment due to a bug in dkms
    - name: dkms mkdeb
      shell: "dkms mkdeb -m {{ item.key }} -v {{ item.value.version }} -k {{ kernel_version }}-{{ kernel_arch }}"
      with_dict: "{{ drivers }}"

    - name: dkms mkbmdeb
      shell: "dkms mkbmdeb -m {{ item.key }} -v {{ item.value.version }} -k {{ kernel_version }}-{{ kernel_arch }}"
      with_dict: "{{ drivers }}"

    - name: retrieve generated bmdeb
      copy:
        remote_src: true
        src: "/var/lib/dkms/{{ item.key }}/{{ item.value.version }}/bmdeb/{{ item.key }}-modules-{{ kernel_version }}-{{ kernel_arch }}_{{ item.value.version }}_{{ kernel_arch }}.deb"
        dest: /vagrant
      with_dict: "{{ drivers }}"
