---

# unarchive
# get_url
- hosts: all
  tasks:
    - name: install necessary resources
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - debhelper
        - dkms
        - bash-completion
        - vim

    - name: install wanted kernels
      apt:
        name: "{{ item[0] }}-{{ item[1].version }}-{{ item[1].arch }}"
      with_nested:
        - [ 'linux-image', 'linux-headers' ]
        - "{{ kernels }}"

    - name: download drivers
      unarchive:
        src: "{{ item.url }}"
        dest: /usr/src
        copy: no
        creates: "/usr/src/{{ item.name }}-{{ item.version }}"
      with_items: "{{ drivers }}"
      when: item.custom_retrieval is not defined

    - name: custom retrieval of drivers
      include: "custom_retrieval/{{ item.custom_retrieval }}
        name={{ item.name}}
        url={{ item.url }}
        version={{ item.version }}"
      with_items: "{{ drivers }}"
      when: item.custom_retrieval is defined

    - name: generate dkms.conf
      template:
        src: dkms.conf.j2
        dest: "/usr/src/{{ item.name }}-{{ item.version }}/dkms.conf"
        force: no
      with_items: "{{ drivers }}"

# add -k option to dkms https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support#DKMS_package_creation

    - name: dkms add
      shell: "dkms add -m {{ item[0].name }} -v {{ item[0].version }} -k {{ item[1].version }}-{{ item[1].arch }}"
      args:
        creates: "/var/lib/dkms/{{ item[0].name }}/{{ item[0].version }}"
      with_nested:
        - "{{ drivers }}"
        - "{{ kernels }}"

    - name: dkms build
      shell: "dkms build -m {{ item[0].name }} -v {{ item[0].version }} -k {{ item[1].version }}-{{ item[1].arch }}"
      with_nested:
        - "{{ drivers }}"
        - "{{ kernels }}"

      # Not working for the moment due to a bug in dkms
    - name: dkms mkdeb
      shell: "dkms mkdeb -m {{ item[0].name }} -v {{ item[0].version }} -k {{ item[1].version }}-{{ item[1].arch }}"
      with_nested:
        - "{{ drivers }}"
        - "{{ kernels }}"

    - name: dkms mkbmdeb
      shell: "dkms mkbmdeb -m {{ item[0].name }} -v {{ item[0].version }} -k {{ item[1].version }}-{{ item[1].arch }}"
      with_nested:
        - "{{ drivers }}"
        - "{{ kernels }}"

    - name: retrieve generated bmdeb
      copy:
        remote_src: true
        src: "/var/lib/dkms/{{ item[0].name }}/{{ item[0].version }}/bmdeb/{{ item[0].name | replace('_', '-') }}-modules-{{ item[1].version }}-{{ item[1].arch }}_{{ item[0].version }}_{{ item[1].arch }}.deb"
        dest: /vagrant
      with_nested:
        - "{{ drivers }}"
        - "{{ kernels }}"
